version: '3'
services:
  portaluser:
    build: .
    volumes:
      - .:/usr/src/app
      - ./node_modules:/usr/src/app/node_modules
    working_dir: /usr/src/app
    ports:
      - 3000:3000
    environment:
      NODE_ENV: development
    entrypoint: ./entrypoint.sh
