version: '3'
services:
  portaluser:
    build: .
    volumes:
      - .:/usr/src/app
      - ./node_modules:/usr/src/app/node_modules
    working_dir: /usr/src/app
    ports:
      - 3000:3000
      - 56745:56745

    environment:
      NODE_ENV: development
    entrypoint: ./entrypoint.sh
  postgres_wf:
    image: postgres:10.7
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: wifree
      POSTGRES_USER: wifree
      POSTGRES_DB: wifree
    volumes:
      - ./etc/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
  mysql_wf:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: wifree
      MYSQL_ROOT_USER: wifree
      MYSQL_DATABASE: wifree
    ports:
      - "3309:3306"
    volumes:
      - ./etc/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
